# Generated by Django 4.2.16 on 2024-09-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_item_options_item_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
